# The URL the site will be built for
base_url = "https://chatoyer.de"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "tabi"
title = "~/chatoyer"

[search]
# Whether to include the title of the page/section in the index.
include_title = true
# Whether to include the description of the page/section in the index.
include_description = true
# Whether to include the path of the page/section in the index.
include_path = true
# Whether to include the rendered content of the page/section in the index.
include_content = true
# At which character to truncate the content to. Useful if you have a lot of pages and the index would
index_format = "elasticlunr_json"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"

[extra]
# Put all your custom variables here
theme_switcher = true
default_theme = "dark"

favicon = "/favicon.svg"
stylesheets = ["services.css"]

email = "bnyro@tutanota.com"
# Decoding requires ~400 bytes of JavaScript. If JS is disabled, the email won't be displayed.
encode_plaintext_email = true  # Setting is ignored if email is already encoded.

menu = [
    { name = "services", url = "/", trailing_slash = true },
    { name = "about", url = "about", trailing_slash = true },
    { name = "donate", url = "donate", trailing_slash = true },
]

socials = [
    { name = "github", url = "https://github.com/bnyro/", icon = "github" },
]

footer_menu = [
    {url = "about", name = "about", trailing_slash = true},
    {url = "privacy", name = "privacy", trailing_slash = true},
    {url = "sitemap.xml", name = "sitemap", trailing_slash = false},
]
